function [D] = ue_speaker()
    %UNTITLED2 Summary of this function goes here
    %   Detailed explanation goes here
    
    radius = 1; %meter
    
    S = ambi_spkr_array(...
        'ue_speaker', ...
        'AER', 'DDM', ...
        'FL', [30, 0, 1], ...
        'FR', [-30, 0, 1], ...
        'RL', [135, 0, 2], ...
        'RR', [-135, 0, 2], ...
        'T', [0, 90, 1]);
        
    C = ambi_channel_definitions(4, 4, 'HV', 'ACN', 'N3D');
    
    D = ambi_run_allrad(S, C);
    
end

