function [D] = st_etienne_9()
    %UNTITLED2 Summary of this function goes here
    %   Detailed explanation goes here
    
    radius = 1; %meter
    
    S = ambi_spkr_array(...
        'st_etienne_9', ...
        'AER', 'DDM', ...
        'BFL', [45, -45, radius], ...
        'BRL', [135, -45, radius], ...
        'BRR', [-135, -45, radius], ...
        'BFR', [-45, -45, radius], ...
        'UFL', [45, 45, radius], ...
        'URL', [135,45,radius], ...
        'URR', [-135, 45, radius], ...
        'UFR', [-45, 45, radius], ...
        'T', [0,90,radius]);
        
    C = ambi_channel_definitions(3, 3, 'HV', 'ACN', 'N3D');
    
    D = ambi_run_allrad(S, C);
    
end

